language: node_js
node_js:
  - "8"
services:
  - mysql
env:
  global:
    - DB_USER=root
    - DB_NAME=sequelize
    - PORT=3000
    - NODE_ENV=test

before_install:
  - mysql -e 'CREATE DATABASE sequelize;'

install:
  - npm install
  - npm install sequelize-cli

script:
  - ./node_modules/.bin/sequelize db:migrate
  - ./node_modules/.bin/sequelize db:seed:all
  - npm run test
