version: 2
jobs:
  build:
    working_directory: ~/zcong1993/sequelize-koa
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:8.0.0
      # CircleCI Mysql
      - image: circleci/mysql:latest
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: sequelize-koa
    steps:
      - checkout
      - run:
          name: Waiting for Mysql to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mysql && exit 1
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install --silent
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run:
          name: db migrate and mock
          environment:
            DB_USER: root
            DB_NAME: sequelize-koa
            PORT: 3000
            NODE_ENV: test
          command: |
            npm install sequelize-cli --silent
            ./node_modules/.bin/sequelize db:migrate
            ./node_modules/.bin/sequelize db:seed:all
            npm run test
